# Site settings
title: PubConf
email: hello@pubconf.io
description: "Rapid-fire funny talks, musical acts, and comedy stunts from amazing developers. At the pub."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pubconf.io" # the base hostname & protocol for your site
image: "/assets/images/global-share.jpg"

newsletter_url: "http://pubconf.us11.list-manage1.com/subscribe?u=33d7399517a3ee3a5e9b679f7&id=05e06dc18c"
youtube_url: "https://www.youtube.com/channel/UCzRi6NoncIBqJzOWT1T-WJw"
twitter_url: "https://twitter.com/pubconf"

# Generic Google Analytics Property. May be overridden by events.
UA: "UA-68386201-1"

facebook_username: pubconf
twitter_username: pubconf

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

sass:
  sass_dir: "assets/css"

exclude:
  - "Gemfile*"
  - "README.md"
  - "vendor" # for travis bullshit.

include:
  - ".well-known"

future: true
collections:
  events:
    output: true
    permalink: /:collection/:path/
  speakers:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event-2019"
